---
jobs:
  categories:
    APP:
      color: "%xm"
    BUILD:
      color: "%xy"
      roles:
      - builder
    BUG:
      color: "%xr"
      roles:
      - coder
    CODE:
      color: "%xy"
      roles:
      - coder
    ALERT:
      color: "%xr"
    MISC:
      color: "%xh"
    PLOT:
      color: "%xc"
    REQ:
      color: "%xm"
    RP:
      color: "%xc"
    SYS:
      color: "%xh"
  status:
    NEW:
      color: "%xg"
    OPEN:
      color: "%xb"
    HOLD:
      color: "%xx%xh"
    DONE:
      color: "%xy"
    ARCHIVED:
      color: "%xx%xh"
  default_status: NEW
  closed_status: DONE
  request_category: REQ
  system_category: SYS
  trouble_category: ALERT
  shortcuts:
    jobs: job
    requests: request
    request/comment: request/respond
    job/comment: job/discuss
    job/submit: job/create
    job/reply: job/respond
    job/open: job/handle
    job/mine: job/filter mine
    job/active: job/filter active
    job/deletecomment: job/deletereply
    job/category: job/cat
    job/all: job/filter all
    request/all: request/filter all
    request/active: request/filter active
    job/unread: job/filter unread
  archive_job_days: 10
  archive_cron:
    day_of_week:
    - Sun
    hour:
    - 4
    minute:
    - 18
  closed_statuses:
  - DONE
  - ARCHIVED
  active_statuses:
  - NEW
  - OPEN
  open_status: OPEN
  archived_status: ARCHIVED
  status_filters: {}
