---
login:
  activity_cron:
    minute:
    - 0
  allow_creation: false
  allow_web_registration: false
  blacklist_cron:
    day:
    - 1
    - 15
    hour:
    - 3
    minute:
    - 0
  creation_not_allowed_message: ''
  guest_role: guest-cannot-login-now
  login_not_allowed_message: ''
  shortcuts:
    logout: quit
    con: connect
    newpassword: password/reset
    conn: connect
    kick: boot
    password/change: password/set
    motd: notice/motd
  portal_requires_registration: false
  guest_disabled_message: ''
  notice_cleanup_cron:
    day:
    - 18
    hour:
    - 2
    minute:
    - 19
  notice_timeout_days: 60
