---
utils:
  shortcuts:
    think: echo
    "@@": keepalive
    "@": keepalive
    shortcut/remove: shortcut/delete
    note/remove: note/delete
    note/update: note/add
    die: dice
    notes: note
    colors: color
    i: echo %% There's no inventory system here.
    in: echo %% There's no inventory system here.
    inv: echo %% There's no inventory system here.
